[Feature-3-7-fe] 유저의 액션(이동, 삭제, 추가, 수정)이 이루어지면 서버에 반영된다.
boostcampwm-2024/web32-BooMap pull request #96
Opened 2024-11-21 10:56 UTC by kimnamheeee

#35 

## 작업 내용

### zustand를 활용하여 SocketSlice 생성
기본적인 소켓 연결, 연결 해제, 이벤트 핸들링을 담당하는 store입니다.

### 소켓 연결 (connection)
HTTP POST `/api/connection`을 통해 새로운 마인드맵 id를 받아오고, SocketSlice의 connectSocket을 호출하여 연결을 시도하는 `handleConnection` 함수를 정의했습니다.
연결될 경우 mindmapId를 포함한 url로 navigate하며, `joinRoom` 이벤트를 통해 서버에 저장되어 있는 마인드맵 데이터를 불러옵니다.

### createNode
유저가 새로운 노드를 생성할 때 발생합니다.
`showNewNode`가 호출될 경우 케이스에 맞추어 이벤트를 발생시키도록 하였으며, 서버에서 응답이 오면 서버가 준 id와 해당 노드의 id를 동기화시킨 다음 `updateNode`를 통해 다른 사용자들에게도 broadcast합니다.

### deleteNode
유저가 노드를 삭제할 때 발생합니다.
`createNode`와 요청 흐름은 동일합니다.
다만 서버에 보낼 때 삭제 대상이 되는 노드의 id를 배열에 담아 보내야 해서, `deleteNode` 함수를 두 부분으로 나누었습니다. (id를 수집하는 `collectNodeIdsToDelete`를 `deleteNode` 내부에 정의하고, id를 먼저 모은 다음 소켓 이벤트를 처리하는 형태로 리팩토링했습니다)

### updateNode
유저가 노드를 이동할 때 / 유저가 노드의 내용을 수정할 때 updateNode 이벤트가 발생합니다.
현재 전역 상태로 관리하고 있는 `NodeData` 전체를 보내면 다른 사용자들에게 보내집니다.

### socket이 updateNode 이벤트를 listen
`updateNode`는 브로드캐스트 형태로 이루어지는 이벤트입니다. socket 객체가 해당 이벤트를 listen하여, 변경사항이 들어올 경우 화면에 반영이 되도록 했습니다.

## 논의하고 싶은 내용

### 추후 작업할 부분
- `SocketSlice` 이름 변경
- `handleSocketEvent`를 호출하도록 로직 통합, 간소화
- 초기에 connection 할 때 에러 핸들링 더 꼼꼼하게

### useHistoryState 관련
가끔 history 배열의 길이보다 pointer 값이 커져서 history 내역을 읽어오지 못하는 경우가 발생하는 것 같습니다. 로직 검토해 보면 좋을 것 같습니다

<img width="500" alt="historyState" src="https://github.com/user-attachments/assets/15131040-58f4-4a5f-9391-4194a9bcb136">

2024-11-21 12:15 UTC, alsgud8311 reviewed
소켓이 zustand store로 구현되어있으니 slice 패턴으로 만들어서 action 관련된 콜백함수를 정의할 수는 없을까용🤔

2024-11-21 12:15 UTC, alsgud8311 commented on client/src/konva_mindmap/components/EditableText.tsx
> +  const socket = SocketSlice.getState().socket;
`const socket = SocketSlice.getState().socket;`방식은 상태를 구독하지 않는 것으로 알고 있는데 의도된 걸까요?

2024-11-21 12:15 UTC, alsgud8311 commented on client/src/konva_mindmap/events/deleteNode.ts
> +    socket.off("deleteNode");
소켓은 어떤 방식으로 통신이 이루어지나요?? 이벤트 리스너를 제거하는게 항상 보이는데 흐름을 잘 모르겠어서요,,ㅠ

2024-11-21 12:15 UTC, alsgud8311 commented on client/src/store/SocketSlice.ts
socketslice보단 socketStore에 가까울 것 같아용

2024-11-21 12:15 UTC, alsgud8311 commented on client/src/konva_mindmap/utils/findRootNodeKey.ts
요거 루트 노드는 항상 0번째 인덱스니까 
parseInt(Object.keys(data)[0]) 요렇게 해도 되지 않을까요?

2024-11-21 12:15 UTC, alsgud8311 commented on client/src/store/SocketSlice.ts
> +  handleSocketEvent: ({ actionType, payload, callback }: HandleSocketEventProps) => {
혹시 요게 어디서 활용되고 있을까요?

2024-11-21 12:18 UTC, alsgud8311 commented
> 가끔 history 배열의 길이보다 pointer 값이 커져서 history 내역을 읽어오지 못하는 경우가 발생하는 것 같습니다. 로직 검토해 보면 좋을 것 같습니다
포인터 값이 배열의 길이를 앞지르는건 히스토리가 저장이 제대로 안되는 경우가 있다는건데.. 한번 다시 봐야겠네요ㅠ 대박 고생하셨습니당

2024-11-21 12:34 UTC, kimnamheeee commented on client/src/store/SocketSlice.ts
추후 변경 예정입니다

2024-11-21 12:35 UTC, kimnamheeee commented on client/src/components/Dashboard/GuestDashBoard.tsx
> +  const { socket, connectSocket } = SocketSlice();
원래 마인드맵 상태랑 통합할 걸 생각해서 socketslice로 이름을 지어 둔 건데 지금은 변경되어야 할 것 같습니다

2024-11-21 12:36 UTC, kimnamheeee commented on client/src/store/SocketSlice.ts
> +  handleSocketEvent: ({ actionType, payload, callback }: HandleSocketEventProps) => {
테스트 후 최종 단계에서 리팩토링 하려고 했는데 아직 반영은 안 되어 있습니다. 이따 createNode deleteNode 등 이벤트 처리에 공통적으로 사용하려고 했습니다

2024-11-21 12:54 UTC, kimnamheeee commented on client/src/konva_mindmap/events/deleteNode.ts
> +    socket.off("deleteNode");
off는 핸들러 중복 등록을 방지하기 위해 사용 중입니다. once를 쓰면 off-on의 효과가 있다고 하던데 잘 안 되더라고요... ㅠ 다시 시도해 봐야 할 것 같기는 합니다

2024-11-21 13:38 UTC, Minju9187 approved these changes
GOOD~!!

2024-11-21 13:41 UTC, Minju9187 requested changes
좀만 더 화이팅!!

2024-11-25 09:52 UTC, kimnamheeee commented
conflict에러 난 거 해결하는 과정에서 커밋이 다 다시 보내져서 리뷰들 뒤로 가버렸네요 😓

2024-11-25 12:42 UTC, kimnamheeee commented on client/src/hooks/useHistoryState.ts
>    );
이 부분은 아직 정확한 시나리오 정리 + 원인 파악 진행 중입니다... 🥹

2024-11-25 14:06 UTC, merged